default_language_version:
  python: python3.8
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black --check -v
      language: python
      types: [ python ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        name: ruff check
